name: CI for ARM64 using Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-22.04  # Ubuntu environment to run Docker

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Run npm install in ARM64 Docker container
        run: |
          docker run --platform linux/arm64 -v $PWD:/workspace -w /workspace node:20 npm install
