name: Build/release Electron app

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            architecture: arm64


    steps:
      - name: Check out Git repository
        uses: actions/checkout@main

      - name: Install Node.js
        uses: actions/setup-node@main
        with:
          node-version: 20
          architecture: ${{ matrix.architecture }}

      - name: Install Dependencies
        run: npm install --arch=arm64

      - name: Build Linux
        if: matrix.os == 'ubuntu-latest'
        run: npm run build:linux --arm64


      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            dist/*.exe
            dist/*.zip
            dist/*.dmg
            dist/*.AppImage
            dist/*.snap
            dist/*.deb
            dist/*.rpm
            dist/*.tar.gz
            dist/*.yml
            dist/*.blockmap
            dist/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
