name: CI for ARM64 using Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest # Ubuntu environment to run Docker

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/arm64

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Install Ruby and fpm dependencies
        run: |
           docker run sudo apt-get update
           docker run sudo apt-get install -y ruby ruby-dev make gcc
           docker run sudo gem install --no-document fpm

      - name: Set PATH for Ruby
        run: |
          docker run echo "export PATH=$PATH:/usr/local/bin" >> $GITHUB_ENV

      - name: Clean npm environment
        run: |
          docker run --platform linux/arm64 -v $PWD:/workspace -w /workspace node:latest npm cache clean --force
          docker run --platform linux/arm64 -v $PWD:/workspace -w /workspace node:latest npm i


      - name: build-linux
        run: docker run --platform linux/arm64 -v $PWD:/workspace -w /workspace node:latest npm run build:linux --arm64

      - name: release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: |
            dist/*.exe
            dist/*.zip
            dist/*.dmg
            dist/*.AppImage
            dist/*.deb
            dist/*.rpm
            dist/*.tar.gz
            dist/*.yml
            dist/*.blockmap
            dist/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
